schema: "classroom50/repo-config/v1"
classroom: "ds112"
assignment: "portfolio"
owner:
  username: "EmilyWangzw"
  id: 327669086
  accepted_at: "2026-09-11T00:23:00Z"
source:
  owner: "mac-ds112-f26"
  owner_id: 323651608
  repo: "portfolio-template"
  branch: "main"
